version: "3.3"

services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${MYSQL_PASSWORD}
      - POSTGRES_DB=${MYSQL_DATABASE}
      - TZ=${TZ}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: application:latest
    ports:
      - "9845:3000"
    environment:
      - MYSQL_HOST=database
      - DATABASE_URL=${DATABASE_URL}
      - TZ=${TZ}

    depends_on:
      - database

    pull_policy: build
    restart: always
